Дане домашнє завдання буде повністю пов'язане з лінійною регресією та її реалізацією. <br/>
Отож розіб'ємо наше домашнє завдання на декілька частин:
- напишіть функцію гіпотези лінійної регресії у векторному вигляді;
- створіть функцію для обчислення функції втрат у векторному вигляді;
- реалізуйте один крок градієнтного спуску;
- знайдіть найкращі параметри w-> для датасету використовуючи написані вами функції, прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;
- знайдіть ці ж параметри за допомогою аналітичного рішення;
- для перевірки спрогнозованих значень, використайте LinearRegression з бібліотеки scikit-learn та порівняйте результати.

In [1406]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler

np.set_printoptions(precision=4)
rng = np.random.default_rng(seed=42)

## Підготовка датасету

In [1407]:
reader = pd.read_csv('datasets/Housing.csv', chunksize=10000)
df = pd.concat(reader, ignore_index=True)
df.drop_duplicates(inplace=True)

In [1408]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [1409]:
df.isna().sum().sort_values(ascending=False)

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [1410]:
df[['price', 'area']].describe()

              price          area
count  5.450000e+02    545.000000
mean   4.766729e+06   5150.541284
std    1.870440e+06   2170.141023
min    1.750000e+06   1650.000000
25%    3.430000e+06   3600.000000
50%    4.340000e+06   4600.000000
75%    5.740000e+06   6360.000000
max    1.330000e+07  16200.000000

In [1411]:
cols_to_convert = df.dtypes[(df.dtypes == 'str')].index
for column in cols_to_convert:
    uniques = df[column].unique().tolist()
    df[column] = df[column].map(lambda x: uniques.index(x))

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,0,0,0,0,0,2,0,0
1,12250000,8960,4,4,4,0,0,0,0,0,3,1,0
2,12250000,9960,3,2,2,0,0,1,0,1,2,0,1
3,12215000,7500,4,2,2,0,0,1,0,0,3,0,0
4,11410000,7420,4,1,2,0,1,1,0,0,2,1,0

## Реалізація функцій регресії, втрат та градієнтного супску

In [1412]:
# функція лінійної регресії
def lin_req_func(x: np.ndarray, w: np.ndarray) -> np.ndarray:
    ones = np.ones((len(x), 1))
    extended_x = np.hstack((ones, x))

    return np.dot(extended_x, w)

In [1413]:
# функція втрат у векторному вигляді
def loss_func(predicted: np.ndarray, actual: np.ndarray) -> np.ndarray:
    return (1 / (2 * len(actual))) * np.sum(np.square(predicted - actual))

In [1414]:
# функція градієнтного спуску
def gradient_func(w: np.ndarray, predicted: np.ndarray, actual: np.ndarray, x: np.ndarray, rate: float) -> np.ndarray:
    m = len(actual)
    ones = np.ones((len(x), 1))
    extended_x = np.hstack((ones, x))

    grad = (1 / m) * ((predicted - actual) @ extended_x)
    return w - rate * grad

## Тестовий прогон власної реалізації лінійнох регресіх
Для тестування використаюмо згенеровані данні з лінійною залежністю та доданим шумом

In [1415]:
n_samples, n_features = 10000, 10

X = rng.uniform(low=1, high=10, size=(n_samples, n_features))
w = rng.random(n_features + 1)

noise = rng.normal(loc=0, scale=0.5, size=n_samples)
Y = w[0] + X @ w[1:] + noise

In [1416]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

prev_loss: float | None = None
loss_diff: float = float('inf')

while loss_diff > 1e-10:
    pred = lin_req_func(X_train, w.T)
    loss = loss_func(pred, y_train)
    w = gradient_func(w, pred, y_train, X_train, 0.0001)

    if prev_loss is not None:
        loss_diff = abs(loss - prev_loss)
    prev_loss = loss

    print(f'Loss: {loss:.12f} | Prev loss: {prev_loss:.12f} | Loss diff: {loss_diff:.12f}')


pred = lin_req_func(X_test, w.T)
print(f'Predicted: {pred[0:5]}')
print(f'Actual: {Y[0:5]}')

Loss: 0.125805032263 | Prev loss: 0.125805032263 | Loss diff: inf
Loss: 0.125804094875 | Prev loss: 0.125804094875 | Loss diff: 0.000000937388
Loss: 0.125803203019 | Prev loss: 0.125803203019 | Loss diff: 0.000000891856
Loss: 0.125802353917 | Prev loss: 0.125802353917 | Loss diff: 0.000000849101
Loss: 0.125801544964 | Prev loss: 0.125801544964 | Loss diff: 0.000000808953
Loss: 0.125800773714 | Prev loss: 0.125800773714 | Loss diff: 0.000000771251
Loss: 0.125800037869 | Prev loss: 0.125800037869 | Loss diff: 0.000000735845
Loss: 0.125799335274 | Prev loss: 0.125799335274 | Loss diff: 0.000000702595
Loss: 0.125798663906 | Prev loss: 0.125798663906 | Loss diff: 0.000000671368
Loss: 0.125798021866 | Prev loss: 0.125798021866 | Loss diff: 0.000000642041
Loss: 0.125797407370 | Prev loss: 0.125797407370 | Loss diff: 0.000000614496
Loss: 0.125796818745 | Prev loss: 0.125796818745 | Loss diff: 0.000000588625
Loss: 0.125796254419 | Prev loss: 0.125796254419 | Loss diff: 0.000000564325
Loss: 0.125795712920 | Prev loss: 0.125795712920 | Loss diff: 0.000000541500
Loss: 0.125795192861 | Prev loss: 0.125795192861 | Loss diff: 0.000000520059
Loss: 0.125794692944 | Prev loss: 0.125794692944 | Loss diff: 0.000000499917
Loss: 0.125794211949 | Prev loss: 0.125794211949 | Loss diff: 0.000000480995
Loss: 0.125793748731 | Prev loss: 0.125793748731 | Loss diff: 0.000000463218
Loss: 0.125793302215 | Prev loss: 0.125793302215 | Loss diff: 0.000000446516
Loss: 0.125792871393 | Prev loss: 0.125792871393 | Loss diff: 0.000000430822
Loss: 0.125792455317 | Prev loss: 0.125792455317 | Loss diff: 0.000000416076
Loss: 0.125792053099 | Prev loss: 0.125792053099 | Loss diff: 0.000000402218
Loss: 0.125791663903 | Prev loss: 0.125791663903 | Loss diff: 0.000000389195
Loss: 0.125791286948 | Prev loss: 0.125791286948 | Loss diff: 0.000000376955
Loss: 0.125790921497 | Prev loss: 0.125790921497 | Loss diff: 0.000000365451
Loss: 0.125790566860 | Prev loss: 0.125790566860 | Loss diff: 0.000000354637
Loss: 0.125790222390 | Prev loss: 0.125790222390 | Loss diff: 0.000000344470
Loss: 0.125789887477 | Prev loss: 0.125789887477 | Loss diff: 0.000000334912
Loss: 0.125789561552 | Prev loss: 0.125789561552 | Loss diff: 0.000000325925
Loss: 0.125789244079 | Prev loss: 0.125789244079 | Loss diff: 0.000000317474
Loss: 0.125788934553 | Prev loss: 0.125788934553 | Loss diff: 0.000000309526
Loss: 0.125788632503 | Prev loss: 0.125788632503 | Loss diff: 0.000000302050
Loss: 0.125788337486 | Prev loss: 0.125788337486 | Loss diff: 0.000000295017
Loss: 0.125788049086 | Prev loss: 0.125788049086 | Loss diff: 0.000000288400
Loss: 0.125787766912 | Prev loss: 0.125787766912 | Loss diff: 0.000000282175
Loss: 0.125787490596 | Prev loss: 0.125787490596 | Loss diff: 0.000000276315
Loss: 0.125787219796 | Prev loss: 0.125787219796 | Loss diff: 0.000000270800
Loss: 0.125786954187 | Prev loss: 0.125786954187 | Loss diff: 0.000000265609
Loss: 0.125786693467 | Prev loss: 0.125786693467 | Loss diff: 0.000000260720
Loss: 0.125786437350 | Prev loss: 0.125786437350 | Loss diff: 0.000000256117
Loss: 0.125786185570 | Prev loss: 0.125786185570 | Loss diff: 0.000000251780
Loss: 0.125785937875 | Prev loss: 0.125785937875 | Loss diff: 0.000000247695
Loss: 0.125785694030 | Prev loss: 0.125785694030 | Loss diff: 0.000000243845
Loss: 0.125785453814 | Prev loss: 0.125785453814 | Loss diff: 0.000000240216
Loss: 0.125785217018 | Prev loss: 0.125785217018 | Loss diff: 0.000000236795
Loss: 0.125784983449 | Prev loss: 0.125784983449 | Loss diff: 0.000000233569
Loss: 0.125784752923 | Prev loss: 0.125784752923 | Loss diff: 0.000000230526
Loss: 0.125784525268 | Prev loss: 0.125784525268 | Loss diff: 0.000000227655
Loss: 0.125784300324 | Prev loss: 0.125784300324 | Loss diff: 0.000000224944
Loss: 0.125784077938 | Prev loss: 0.125784077938 | Loss diff: 0.000000222386
Loss: 0.125783857969 | Prev loss: 0.125783857969 | Loss diff: 0.000000219969
Loss: 0.125783640283 | Prev loss: 0.125783640283 | Loss diff: 0.000000217686
Loss: 0.125783424756 | Prev loss: 0.125783424756 | Loss diff: 0.000000215528
Loss: 0.125783211268 | Prev loss: 0.125783211268 | Loss diff: 0.000000213487
Loss: 0.125782999711 | Prev loss: 0.125782999711 | Loss diff: 0.000000211557
Loss: 0.125782789979 | Prev loss: 0.125782789979 | Loss diff: 0.000000209731
Loss: 0.125782581977 | Prev loss: 0.125782581977 | Loss diff: 0.000000208002
Loss: 0.125782375613 | Prev loss: 0.125782375613 | Loss diff: 0.000000206365
Loss: 0.125782170800 | Prev loss: 0.125782170800 | Loss diff: 0.000000204813
Loss: 0.125781967459 | Prev loss: 0.125781967459 | Loss diff: 0.000000203341
Loss: 0.125781765513 | Prev loss: 0.125781765513 | Loss diff: 0.000000201946
Loss: 0.125781564892 | Prev loss: 0.125781564892 | Loss diff: 0.000000200621
Loss: 0.125781365529 | Prev loss: 0.125781365529 | Loss diff: 0.000000199363
Loss: 0.125781167361 | Prev loss: 0.125781167361 | Loss diff: 0.000000198168
Loss: 0.125780970330 | Prev loss: 0.125780970330 | Loss diff: 0.000000197031
Loss: 0.125780774381 | Prev loss: 0.125780774381 | Loss diff: 0.000000195950
Loss: 0.125780579461 | Prev loss: 0.125780579461 | Loss diff: 0.000000194920
Loss: 0.125780385522 | Prev loss: 0.125780385522 | Loss diff: 0.000000193939
Loss: 0.125780192518 | Prev loss: 0.125780192518 | Loss diff: 0.000000193004
Loss: 0.125780000407 | Prev loss: 0.125780000407 | Loss diff: 0.000000192111
Loss: 0.125779809147 | Prev loss: 0.125779809147 | Loss diff: 0.000000191259
Loss: 0.125779618702 | Prev loss: 0.125779618702 | Loss diff: 0.000000190445
Loss: 0.125779429035 | Prev loss: 0.125779429035 | Loss diff: 0.000000189667
Loss: 0.125779240113 | Prev loss: 0.125779240113 | Loss diff: 0.000000188922
Loss: 0.125779051906 | Prev loss: 0.125779051906 | Loss diff: 0.000000188208
Loss: 0.125778864382 | Prev loss: 0.125778864382 | Loss diff: 0.000000187523
Loss: 0.125778677516 | Prev loss: 0.125778677516 | Loss diff: 0.000000186867
Loss: 0.125778491280 | Prev loss: 0.125778491280 | Loss diff: 0.000000186236
Loss: 0.125778305650 | Prev loss: 0.125778305650 | Loss diff: 0.000000185630
Loss: 0.125778120604 | Prev loss: 0.125778120604 | Loss diff: 0.000000185046
Loss: 0.125777936120 | Prev loss: 0.125777936120 | Loss diff: 0.000000184484
Loss: 0.125777752177 | Prev loss: 0.125777752177 | Loss diff: 0.000000183943
Loss: 0.125777568756 | Prev loss: 0.125777568756 | Loss diff: 0.000000183420
Loss: 0.125777385841 | Prev loss: 0.125777385841 | Loss diff: 0.000000182916
Loss: 0.125777203413 | Prev loss: 0.125777203413 | Loss diff: 0.000000182428
Loss: 0.125777021457 | Prev loss: 0.125777021457 | Loss diff: 0.000000181956
Loss: 0.125776839959 | Prev loss: 0.125776839959 | Loss diff: 0.000000181498
Loss: 0.125776658904 | Prev loss: 0.125776658904 | Loss diff: 0.000000181055
Loss: 0.125776478279 | Prev loss: 0.125776478279 | Loss diff: 0.000000180625
Loss: 0.125776298071 | Prev loss: 0.125776298071 | Loss diff: 0.000000180207
Loss: 0.125776118271 | Prev loss: 0.125776118271 | Loss diff: 0.000000179801
Loss: 0.125775938865 | Prev loss: 0.125775938865 | Loss diff: 0.000000179406
Loss: 0.125775759845 | Prev loss: 0.125775759845 | Loss diff: 0.000000179020
Loss: 0.125775581200 | Prev loss: 0.125775581200 | Loss diff: 0.000000178645
Loss: 0.125775402921 | Prev loss: 0.125775402921 | Loss diff: 0.000000178278
Loss: 0.125775225001 | Prev loss: 0.125775225001 | Loss diff: 0.000000177921
Loss: 0.125775047430 | Prev loss: 0.125775047430 | Loss diff: 0.000000177571
Loss: 0.125774870202 | Prev loss: 0.125774870202 | Loss diff: 0.000000177228
Loss: 0.125774693309 | Prev loss: 0.125774693309 | Loss diff: 0.000000176893
Loss: 0.125774516744 | Prev loss: 0.125774516744 | Loss diff: 0.000000176565
Loss: 0.125774340502 | Prev loss: 0.125774340502 | Loss diff: 0.000000176242
Loss: 0.125774164576 | Prev loss: 0.125774164576 | Loss diff: 0.000000175926
Loss: 0.125773988961 | Prev loss: 0.125773988961 | Loss diff: 0.000000175615
Loss: 0.125773813651 | Prev loss: 0.125773813651 | Loss diff: 0.000000175310
Loss: 0.125773638642 | Prev loss: 0.125773638642 | Loss diff: 0.000000175009
Loss: 0.125773463928 | Prev loss: 0.125773463928 | Loss diff: 0.000000174713
Loss: 0.125773289506 | Prev loss: 0.125773289506 | Loss diff: 0.000000174422
Loss: 0.125773115372 | Prev loss: 0.125773115372 | Loss diff: 0.000000174135
Loss: 0.125772941521 | Prev loss: 0.125772941521 | Loss diff: 0.000000173851
Loss: 0.125772767949 | Prev loss: 0.125772767949 | Loss diff: 0.000000173571
Loss: 0.125772594654 | Prev loss: 0.125772594654 | Loss diff: 0.000000173295
Loss: 0.125772421632 | Prev loss: 0.125772421632 | Loss diff: 0.000000173022
Loss: 0.125772248879 | Prev loss: 0.125772248879 | Loss diff: 0.000000172752
Loss: 0.125772076394 | Prev loss: 0.125772076394 | Loss diff: 0.000000172485
Loss: 0.125771904173 | Prev loss: 0.125771904173 | Loss diff: 0.000000172221
Loss: 0.125771732213 | Prev loss: 0.125771732213 | Loss diff: 0.000000171960
Loss: 0.125771560512 | Prev loss: 0.125771560512 | Loss diff: 0.000000171701
Loss: 0.125771389068 | Prev loss: 0.125771389068 | Loss diff: 0.000000171444
Loss: 0.125771217879 | Prev loss: 0.125771217879 | Loss diff: 0.000000171190
Loss: 0.125771046942 | Prev loss: 0.125771046942 | Loss diff: 0.000000170937
Loss: 0.125770876255 | Prev loss: 0.125770876255 | Loss diff: 0.000000170687
Loss: 0.125770705817 | Prev loss: 0.125770705817 | Loss diff: 0.000000170438
Loss: 0.125770535625 | Prev loss: 0.125770535625 | Loss diff: 0.000000170191
Loss: 0.125770365679 | Prev loss: 0.125770365679 | Loss diff: 0.000000169946
Loss: 0.125770195976 | Prev loss: 0.125770195976 | Loss diff: 0.000000169703
Loss: 0.125770026515 | Prev loss: 0.125770026515 | Loss diff: 0.000000169461
Loss: 0.125769857295 | Prev loss: 0.125769857295 | Loss diff: 0.000000169220
Loss: 0.125769688313 | Prev loss: 0.125769688313 | Loss diff: 0.000000168981
Loss: 0.125769519570 | Prev loss: 0.125769519570 | Loss diff: 0.000000168744
Loss: 0.125769351063 | Prev loss: 0.125769351063 | Loss diff: 0.000000168507
Loss: 0.125769182791 | Prev loss: 0.125769182791 | Loss diff: 0.000000168272
Loss: 0.125769014754 | Prev loss: 0.125769014754 | Loss diff: 0.000000168037
Loss: 0.125768846950 | Prev loss: 0.125768846950 | Loss diff: 0.000000167804
Loss: 0.125768679377 | Prev loss: 0.125768679377 | Loss diff: 0.000000167572
Loss: 0.125768512036 | Prev loss: 0.125768512036 | Loss diff: 0.000000167341
Loss: 0.125768344925 | Prev loss: 0.125768344925 | Loss diff: 0.000000167111
Loss: 0.125768178044 | Prev loss: 0.125768178044 | Loss diff: 0.000000166882
Loss: 0.125768011391 | Prev loss: 0.125768011391 | Loss diff: 0.000000166653
Loss: 0.125767844965 | Prev loss: 0.125767844965 | Loss diff: 0.000000166426
Loss: 0.125767678766 | Prev loss: 0.125767678766 | Loss diff: 0.000000166199
Loss: 0.125767512793 | Prev loss: 0.125767512793 | Loss diff: 0.000000165973
Loss: 0.125767347046 | Prev loss: 0.125767347046 | Loss diff: 0.000000165748
Loss: 0.125767181523 | Prev loss: 0.125767181523 | Loss diff: 0.000000165523
Loss: 0.125767016223 | Prev loss: 0.125767016223 | Loss diff: 0.000000165299
Loss: 0.125766851147 | Prev loss: 0.125766851147 | Loss diff: 0.000000165076
Loss: 0.125766686294 | Prev loss: 0.125766686294 | Loss diff: 0.000000164853
Loss: 0.125766521663 | Prev loss: 0.125766521663 | Loss diff: 0.000000164631
Loss: 0.125766357253 | Prev loss: 0.125766357253 | Loss diff: 0.000000164410
Loss: 0.125766193064 | Prev loss: 0.125766193064 | Loss diff: 0.000000164189
Loss: 0.125766029095 | Prev loss: 0.125766029095 | Loss diff: 0.000000163969
Loss: 0.125765865346 | Prev loss: 0.125765865346 | Loss diff: 0.000000163749
Loss: 0.125765701816 | Prev loss: 0.125765701816 | Loss diff: 0.000000163530
Loss: 0.125765538505 | Prev loss: 0.125765538505 | Loss diff: 0.000000163311
Loss: 0.125765375412 | Prev loss: 0.125765375412 | Loss diff: 0.000000163093
Loss: 0.125765212536 | Prev loss: 0.125765212536 | Loss diff: 0.000000162875
Loss: 0.125765049878 | Prev loss: 0.125765049878 | Loss diff: 0.000000162658
Loss: 0.125764887437 | Prev loss: 0.125764887437 | Loss diff: 0.000000162441
Loss: 0.125764725212 | Prev loss: 0.125764725212 | Loss diff: 0.000000162225
Loss: 0.125764563203 | Prev loss: 0.125764563203 | Loss diff: 0.000000162009
Loss: 0.125764401410 | Prev loss: 0.125764401410 | Loss diff: 0.000000161793
Loss: 0.125764239831 | Prev loss: 0.125764239831 | Loss diff: 0.000000161578
Loss: 0.125764078468 | Prev loss: 0.125764078468 | Loss diff: 0.000000161364
Loss: 0.125763917318 | Prev loss: 0.125763917318 | Loss diff: 0.000000161149
Loss: 0.125763756383 | Prev loss: 0.125763756383 | Loss diff: 0.000000160936
Loss: 0.125763595661 | Prev loss: 0.125763595661 | Loss diff: 0.000000160722
Loss: 0.125763435152 | Prev loss: 0.125763435152 | Loss diff: 0.000000160509
Loss: 0.125763274855 | Prev loss: 0.125763274855 | Loss diff: 0.000000160296
Loss: 0.125763114772 | Prev loss: 0.125763114772 | Loss diff: 0.000000160084
Loss: 0.125762954900 | Prev loss: 0.125762954900 | Loss diff: 0.000000159872
Loss: 0.125762795240 | Prev loss: 0.125762795240 | Loss diff: 0.000000159660
Loss: 0.125762635791 | Prev loss: 0.125762635791 | Loss diff: 0.000000159449
Loss: 0.125762476553 | Prev loss: 0.125762476553 | Loss diff: 0.000000159238
Loss: 0.125762317526 | Prev loss: 0.125762317526 | Loss diff: 0.000000159027
Loss: 0.125762158709 | Prev loss: 0.125762158709 | Loss diff: 0.000000158817
Loss: 0.125762000102 | Prev loss: 0.125762000102 | Loss diff: 0.000000158607
Loss: 0.125761841705 | Prev loss: 0.125761841705 | Loss diff: 0.000000158397
Loss: 0.125761683517 | Prev loss: 0.125761683517 | Loss diff: 0.000000158188
Loss: 0.125761525538 | Prev loss: 0.125761525538 | Loss diff: 0.000000157979
Loss: 0.125761367768 | Prev loss: 0.125761367768 | Loss diff: 0.000000157770
Loss: 0.125761210206 | Prev loss: 0.125761210206 | Loss diff: 0.000000157562
Loss: 0.125761052853 | Prev loss: 0.125761052853 | Loss diff: 0.000000157354
Loss: 0.125760895707 | Prev loss: 0.125760895707 | Loss diff: 0.000000157146
Loss: 0.125760738768 | Prev loss: 0.125760738768 | Loss diff: 0.000000156939
Loss: 0.125760582036 | Prev loss: 0.125760582036 | Loss diff: 0.000000156731
Loss: 0.125760425512 | Prev loss: 0.125760425512 | Loss diff: 0.000000156525
Loss: 0.125760269194 | Prev loss: 0.125760269194 | Loss diff: 0.000000156318
Loss: 0.125760113082 | Prev loss: 0.125760113082 | Loss diff: 0.000000156112
Loss: 0.125759957176 | Prev loss: 0.125759957176 | Loss diff: 0.000000155906
Loss: 0.125759801476 | Prev loss: 0.125759801476 | Loss diff: 0.000000155700
Loss: 0.125759645981 | Prev loss: 0.125759645981 | Loss diff: 0.000000155495
Loss: 0.125759490691 | Prev loss: 0.125759490691 | Loss diff: 0.000000155290
Loss: 0.125759335606 | Prev loss: 0.125759335606 | Loss diff: 0.000000155085
Loss: 0.125759180726 | Prev loss: 0.125759180726 | Loss diff: 0.000000154881
Loss: 0.125759026049 | Prev loss: 0.125759026049 | Loss diff: 0.000000154676
Loss: 0.125758871577 | Prev loss: 0.125758871577 | Loss diff: 0.000000154472
Loss: 0.125758717308 | Prev loss: 0.125758717308 | Loss diff: 0.000000154269
Loss: 0.125758563243 | Prev loss: 0.125758563243 | Loss diff: 0.000000154065
Loss: 0.125758409380 | Prev loss: 0.125758409380 | Loss diff: 0.000000153862
Loss: 0.125758255721 | Prev loss: 0.125758255721 | Loss diff: 0.000000153660
Loss: 0.125758102264 | Prev loss: 0.125758102264 | Loss diff: 0.000000153457
Loss: 0.125757949009 | Prev loss: 0.125757949009 | Loss diff: 0.000000153255
Loss: 0.125757795956 | Prev loss: 0.125757795956 | Loss diff: 0.000000153053
Loss: 0.125757643105 | Prev loss: 0.125757643105 | Loss diff: 0.000000152851
Loss: 0.125757490455 | Prev loss: 0.125757490455 | Loss diff: 0.000000152650
Loss: 0.125757338007 | Prev loss: 0.125757338007 | Loss diff: 0.000000152449
Loss: 0.125757185759 | Prev loss: 0.125757185759 | Loss diff: 0.000000152248
Loss: 0.125757033712 | Prev loss: 0.125757033712 | Loss diff: 0.000000152047
Loss: 0.125756881865 | Prev loss: 0.125756881865 | Loss diff: 0.000000151847
Loss: 0.125756730219 | Prev loss: 0.125756730219 | Loss diff: 0.000000151647
Loss: 0.125756578772 | Prev loss: 0.125756578772 | Loss diff: 0.000000151447
Loss: 0.125756427524 | Prev loss: 0.125756427524 | Loss diff: 0.000000151247
Loss: 0.125756276476 | Prev loss: 0.125756276476 | Loss diff: 0.000000151048
Loss: 0.125756125627 | Prev loss: 0.125756125627 | Loss diff: 0.000000150849
Loss: 0.125755974976 | Prev loss: 0.125755974976 | Loss diff: 0.000000150650
Loss: 0.125755824524 | Prev loss: 0.125755824524 | Loss diff: 0.000000150452
Loss: 0.125755674270 | Prev loss: 0.125755674270 | Loss diff: 0.000000150254
Loss: 0.125755524215 | Prev loss: 0.125755524215 | Loss diff: 0.000000150056
Loss: 0.125755374356 | Prev loss: 0.125755374356 | Loss diff: 0.000000149858
Loss: 0.125755224695 | Prev loss: 0.125755224695 | Loss diff: 0.000000149661
Loss: 0.125755075232 | Prev loss: 0.125755075232 | Loss diff: 0.000000149464
Loss: 0.125754925965 | Prev loss: 0.125754925965 | Loss diff: 0.000000149267
Loss: 0.125754776894 | Prev loss: 0.125754776894 | Loss diff: 0.000000149070
Loss: 0.125754628020 | Prev loss: 0.125754628020 | Loss diff: 0.000000148874
Loss: 0.125754479343 | Prev loss: 0.125754479343 | Loss diff: 0.000000148678
Loss: 0.125754330861 | Prev loss: 0.125754330861 | Loss diff: 0.000000148482
Loss: 0.125754182574 | Prev loss: 0.125754182574 | Loss diff: 0.000000148287
Loss: 0.125754034483 | Prev loss: 0.125754034483 | Loss diff: 0.000000148091
Loss: 0.125753886587 | Prev loss: 0.125753886587 | Loss diff: 0.000000147896
Loss: 0.125753738885 | Prev loss: 0.125753738885 | Loss diff: 0.000000147701
Loss: 0.125753591378 | Prev loss: 0.125753591378 | Loss diff: 0.000000147507
Loss: 0.125753444066 | Prev loss: 0.125753444066 | Loss diff: 0.000000147313
Loss: 0.125753296947 | Prev loss: 0.125753296947 | Loss diff: 0.000000147119
Loss: 0.125753150022 | Prev loss: 0.125753150022 | Loss diff: 0.000000146925
Loss: 0.125753003291 | Prev loss: 0.125753003291 | Loss diff: 0.000000146731
Loss: 0.125752856753 | Prev loss: 0.125752856753 | Loss diff: 0.000000146538
Loss: 0.125752710408 | Prev loss: 0.125752710408 | Loss diff: 0.000000146345
Loss: 0.125752564255 | Prev loss: 0.125752564255 | Loss diff: 0.000000146152
Loss: 0.125752418295 | Prev loss: 0.125752418295 | Loss diff: 0.000000145960
Loss: 0.125752272528 | Prev loss: 0.125752272528 | Loss diff: 0.000000145768
Loss: 0.125752126952 | Prev loss: 0.125752126952 | Loss diff: 0.000000145576
Loss: 0.125751981568 | Prev loss: 0.125751981568 | Loss diff: 0.000000145384
Loss: 0.125751836375 | Prev loss: 0.125751836375 | Loss diff: 0.000000145193
Loss: 0.125751691374 | Prev loss: 0.125751691374 | Loss diff: 0.000000145001
Loss: 0.125751546563 | Prev loss: 0.125751546563 | Loss diff: 0.000000144810
Loss: 0.125751401944 | Prev loss: 0.125751401944 | Loss diff: 0.000000144620
Loss: 0.125751257514 | Prev loss: 0.125751257514 | Loss diff: 0.000000144429
Loss: 0.125751113275 | Prev loss: 0.125751113275 | Loss diff: 0.000000144239
Loss: 0.125750969226 | Prev loss: 0.125750969226 | Loss diff: 0.000000144049
Loss: 0.125750825366 | Prev loss: 0.125750825366 | Loss diff: 0.000000143860
Loss: 0.125750681696 | Prev loss: 0.125750681696 | Loss diff: 0.000000143670
Loss: 0.125750538215 | Prev loss: 0.125750538215 | Loss diff: 0.000000143481
Loss: 0.125750394923 | Prev loss: 0.125750394923 | Loss diff: 0.000000143292
Loss: 0.125750251820 | Prev loss: 0.125750251820 | Loss diff: 0.000000143103
Loss: 0.125750108905 | Prev loss: 0.125750108905 | Loss diff: 0.000000142915
Loss: 0.125749966179 | Prev loss: 0.125749966179 | Loss diff: 0.000000142727
Loss: 0.125749823640 | Prev loss: 0.125749823640 | Loss diff: 0.000000142539
Loss: 0.125749681289 | Prev loss: 0.125749681289 | Loss diff: 0.000000142351
Loss: 0.125749539126 | Prev loss: 0.125749539126 | Loss diff: 0.000000142164
Loss: 0.125749397149 | Prev loss: 0.125749397149 | Loss diff: 0.000000141976

## Нормалізація та розбиття датасету

In [1417]:
features = ['area', 'bedrooms', 'bathrooms']
to_predict = ['price']

In [1418]:
df[[*to_predict, *features]].head()

      price  area  bedrooms  bathrooms
0  13300000  7420         4          2
1  12250000  8960         4          4
2  12250000  9960         3          2
3  12215000  7500         4          2
4  11410000  7420         4          1

In [1419]:
scaler = StandardScaler()
df_scaled = df[[*to_predict, *features]].copy()
df_scaled[[*to_predict, *features]] = scaler.fit_transform(df[[*to_predict, *features]])

df_scaled.head()

      price      area  bedrooms  bathrooms
0  4.566365  1.046726  1.403419   1.421812
1  4.004484  1.757010  1.403419   5.405809
2  4.004484  2.218232  0.047278   1.421812
3  3.985755  1.083624  1.403419   1.421812
4  3.554979  1.046726  1.403419  -0.570187

In [1420]:
X = df_scaled[features].to_numpy()
Y = df_scaled[to_predict].to_numpy().T[0]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

## Моделювання за допомогою власної реалізації лінійної регресії

In [1421]:
w = rng.random((X_train.shape[1] + 1))

prev_loss: float | None = None
loss_diff: float = float('inf')

while loss_diff > 1e-10:
    pred = lin_req_func(X_train, w.T)
    loss = loss_func(pred, y_train)
    w = gradient_func(w, pred, y_train, X_train, 0.5)

    if prev_loss is not None:
        loss_diff = abs(loss - prev_loss)
    prev_loss = loss

    print(f'Loss: {loss:.12f} | Prev loss: {prev_loss:.12f} | Loss diff: {loss_diff:.12f}')

Loss: 0.943035372129 | Prev loss: 0.943035372129 | Loss diff: inf
Loss: 0.336924205236 | Prev loss: 0.336924205236 | Loss diff: 0.606111166893
Loss: 0.247969225696 | Prev loss: 0.247969225696 | Loss diff: 0.088954979540
Loss: 0.229529031628 | Prev loss: 0.229529031628 | Loss diff: 0.018440194068
Loss: 0.225046455100 | Prev loss: 0.225046455100 | Loss diff: 0.004482576529
Loss: 0.223890876774 | Prev loss: 0.223890876774 | Loss diff: 0.001155578325
Loss: 0.223583966876 | Prev loss: 0.223583966876 | Loss diff: 0.000306909898
Loss: 0.223500040566 | Prev loss: 0.223500040566 | Loss diff: 0.000083926310
Loss: 0.223476139214 | Prev loss: 0.223476139214 | Loss diff: 0.000023901352
Loss: 0.223468916543 | Prev loss: 0.223468916543 | Loss diff: 0.000007222672
Loss: 0.223466550461 | Prev loss: 0.223466550461 | Loss diff: 0.000002366081
Loss: 0.223465696895 | Prev loss: 0.223465696895 | Loss diff: 0.000000853566
Loss: 0.223465357416 | Prev loss: 0.223465357416 | Loss diff: 0.000000339479
Loss: 0.223465210699 | Prev loss: 0.223465210699 | Loss diff: 0.000000146717
Loss: 0.223465143306 | Prev loss: 0.223465143306 | Loss diff: 0.000000067394
Loss: 0.223465111085 | Prev loss: 0.223465111085 | Loss diff: 0.000000032221
Loss: 0.223465095299 | Prev loss: 0.223465095299 | Loss diff: 0.000000015786
Loss: 0.223465087454 | Prev loss: 0.223465087454 | Loss diff: 0.000000007845
Loss: 0.223465083522 | Prev loss: 0.223465083522 | Loss diff: 0.000000003931
Loss: 0.223465081543 | Prev loss: 0.223465081543 | Loss diff: 0.000000001979
Loss: 0.223465080544 | Prev loss: 0.223465080544 | Loss diff: 0.000000000999
Loss: 0.223465080039 | Prev loss: 0.223465080039 | Loss diff: 0.000000000505
Loss: 0.223465079784 | Prev loss: 0.223465079784 | Loss diff: 0.000000000256
Loss: 0.223465079654 | Prev loss: 0.223465079654 | Loss diff: 0.000000000129
Loss: 0.223465079589 | Prev loss: 0.223465079589 | Loss diff: 0.000000000066

In [1422]:
y_pred = lin_req_func(X_test, w.T)
error = mean_squared_error(y_test, y_pred)
print(f'Mean squared error: {error:.12f}')

print(f'Coefficients: {w}')

Mean squared error: 0.787496369084
Coefficients: [-0.0163  0.4008  0.1421  0.3821]

In [1423]:
predicted_data = scaler.inverse_transform(np.hstack((y_pred.reshape(-1, 1), X_test)))
real_data = scaler.inverse_transform(np.hstack((y_test.reshape(-1, 1), X_test)))

predicted_df = pd.DataFrame(predicted_data, columns=['predicted_price', *features])
real_df = pd.DataFrame(real_data, columns=['real_price', *features])

real_df['predicted_price'] = predicted_df['predicted_price']
real_df[['predicted_price', 'real_price']].head()

   predicted_price  real_price
0     6.383163e+06   4060000.0
1     6.230229e+06   6650000.0
2     3.597876e+06   3710000.0
3     4.289739e+06   6440000.0
4     3.930453e+06   2800000.0

## Моедлювання за допомогою sklearn LinearRegression

In [1424]:
reg = sklearn.linear_model.LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [1425]:
y_pred = reg.predict(X_test)
error = mean_squared_error(y_test, y_pred)
print(f'Mean squared error: {error:.12f}')

print(f'Coefficients: {reg.coef_}')
print(f'Intercept: {reg.intercept_:.4f}')

Mean squared error: 0.787497719214
Coefficients: [0.4008 0.1421 0.3821]
Intercept: -0.0163

In [1426]:
predicted_data = scaler.inverse_transform(np.hstack((y_pred.reshape(-1, 1), X_test)))
real_data = scaler.inverse_transform(np.hstack((y_test.reshape(-1, 1), X_test)))

predicted_df = pd.DataFrame(predicted_data, columns=['predicted_price',*features])
real_df = pd.DataFrame(real_data, columns=['real_price', *features])

real_df['predicted_price'] = predicted_df['predicted_price']
real_df[['predicted_price', 'real_price']].head()

   predicted_price  real_price
0     6.383168e+06   4060000.0
1     6.230250e+06   6650000.0
2     3.597885e+06   3710000.0
3     4.289731e+06   6440000.0
4     3.930446e+06   2800000.0

## Аналітичне рішення

In [1427]:
X_train_extended = np.hstack((np.ones((len(X_train), 1)), X_train))
w = np.linalg.solve(X_train_extended.T @ X_train_extended, X_train_extended.T @ y_train)

In [1428]:
y_pred = lin_req_func(X_test, w.T)
error = mean_squared_error(y_test, y_pred)
print(f'Mean squared error: {error:.12f}')

print(f'Coefficients: {reg.coef_}')
print(f'Intercept: {reg.intercept_:.4f}')

Mean squared error: 0.787497719214
Coefficients: [0.4008 0.1421 0.3821]
Intercept: -0.0163

In [1429]:
predicted_data = scaler.inverse_transform(np.hstack((y_pred.reshape(-1, 1), X_test)))
real_data = scaler.inverse_transform(np.hstack((y_test.reshape(-1, 1), X_test)))

predicted_df = pd.DataFrame(predicted_data, columns=['predicted_price',*features])
real_df = pd.DataFrame(real_data, columns=['real_price', *features])

real_df['predicted_price'] = predicted_df['predicted_price']
real_df[['predicted_price', 'real_price']].head()

   predicted_price  real_price
0     6.383168e+06   4060000.0
1     6.230250e+06   6650000.0
2     3.597885e+06   3710000.0
3     4.289731e+06   6440000.0
4     3.930446e+06   2800000.0